//
//  SalamModels.swift
//  CarOwnership
//
//  Created by Amirreza Eghtedari on 07.05.20.
//  Copyright (c) 2020 Amirreza Eghtedari. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Salam
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
