//
//  SalamPresenter.swift
//  CarOwnership
//
//  Created by Amirreza Eghtedari on 07.05.20.
//  Copyright (c) 2020 Amirreza Eghtedari. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SalamPresentationLogic
{
  func presentSomething(response: Salam.Something.Response)
}

class SalamPresenter: SalamPresentationLogic
{
  weak var viewController: SalamDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Salam.Something.Response)
  {
    let viewModel = Salam.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
