//
//  SalamInteractor.swift
//  CarOwnership
//
//  Created by Amirreza Eghtedari on 07.05.20.
//  Copyright (c) 2020 Amirreza Eghtedari. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SalamBusinessLogic
{
  func doSomething(request: Salam.Something.Request)
}

protocol SalamDataStore
{
  //var name: String { get set }
}

class SalamInteractor: SalamBusinessLogic, SalamDataStore
{
  var presenter: SalamPresentationLogic?
  var worker: SalamWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Salam.Something.Request)
  {
    worker = SalamWorker()
    worker?.doSomeWork()
    
    let response = Salam.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
