//
//  SalamRouter.swift
//  CarOwnership
//
//  Created by Amirreza Eghtedari on 07.05.20.
//  Copyright (c) 2020 Amirreza Eghtedari. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SalamRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SalamDataPassing
{
  var dataStore: SalamDataStore? { get }
}

class SalamRouter: NSObject, SalamRoutingLogic, SalamDataPassing
{
  weak var viewController: SalamViewController?
  var dataStore: SalamDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SalamViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SalamDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
